INSERT INTO departments (department_name)
VALUES ("Human Resources"),
       ("Information Technology"),
       ("Accounting"),
       ("Marketing"),
       ("Production");

INSERT INTO roles (department_id, title, salary)
VALUES (1, "Employment Manager", 72934.68), 
       (1, "Recruiter", 52060.33), 
       (1, "Recruitment manager", 21580.97), 
       (2, "Computer systems manager", 159010.92), 
       (2, "Network architect", 132006.76), 
       (2, "Systems analyst", 69010.86), 
       (3, "Accounting manager", 118178.24), 
       (3, "Accounts payable clerk", 33963.43), 
       (3, "Assistant controller", 156574.76), 
       (4, "Chief marketing officer", 341815.56), 
       (4, "Director of marketing", 177301.34), 
       (4, "Marketing analyst", 59400.89), 
       (5, "Assembly Supervisor", 65842.42), 
       (5, "Assistant Plant Manager", 91126.43), 
       (5, "Chief Manufacturing Executive", 290300.76);


INSERT INTO employees (role_id, first_name, last_name, manager_id)
VALUE   (1, "Juliette", "Noble", NULL),         
        (2, "Donavan", "Nicholson", 3),         
        (3, "Katherine", "Benton", 1),         
        (4, "Ali", "Garza", NULL),         
        (5, "Iris", "Rocha", 4),        
        (6, "Livia", "Leon", 4),        
        (7, "Kenneth", "Adkins", NULL),         
        (8, "Arianna", "Andersen", 7),        
        (9, "Reagan", "Henderson", 7),         
        (10, "Rafael", "Lindsey", NULL), 
        (11, "Lexi", "Meyers", 10), 
        (12, "Ayaan", "Hubbard", 10), 
        (13, "Calvin", "Sparks", 15), 
        (14, "Aimee", "Mora", 15), 
        (15, "Rodney", "Holmes", NULL), 
        (2, "Gracie", "Houston", 3), 
        (5, "Clare", "Logan", 4), 
        (6, "Kamari", "Hobbs", 4), 
        (8, "Laurel", "Waters", 7), 
        (12, "Lilianna", "Compton", 10), 
        (8, "Hugh", "Alvarado", 7), 
        (2, "Meredith", "Sharp", 3), 
        (6, "Cameron", "Mcfarland", 4),
        (5, "Averie", "Chavez", 4), 
        (5, "Pierce", "Meyers", 4), 
        (8, "Kiley", "Benjamin", 7);
