INSERT INTO departments (department_name)
VALUES ("Human Resources"),
       ("Information Technology"),
       ("Accounting"),
       ("Marketing"),
       ("Production");

INSERT INTO roles (title, salary)
VALUES ("Employment Manager", 72934.68),
       ("Recruiter", 52060.33),
       ("Recruitment manager", 21580.97),
       ("HR analyst", 52860.23),
       ("HR coordinator", 57833.87),
       ("Employee relation manager", 75713.90),
       ("Exective HR", 229064.65),
       ("Computer systems manager", 159010.92),
       ("Network architect", 132006.76),
       ("Systems analyst", 69010.86),
       ("IT coordinator", 59553.43),
       ("Network administrator", 63314.45),
       ("Network engineer", 91388.10),
       ("Service desk analyst", 39375.09),
       ("System administrator", 78503.23),
       ("Accounting manager", 118178.24),
       ("Accounts payable clerk", 33963.43),
       ("Assistant controller", 156574.76),
       ("Billing clerk", 34500.23),
       ("Bookkeeper", 41883.53),
       ("Controller", 241154.24),
       ("Cost accountant", 66016.09),
       ("Collections manager", 105514.89),
       ("Chief marketing officer", 341815.56),
       ("Director of marketing", 177301.34),
       ("Marketing analyst", 59400.89),
       ("Marketing coordinator", 48314.12),
       ("Marketing consultant", 67700.76),
       ("Marketing manager", 114604.76),
       ("Promotions manager", 133380),
       ("Marketing specialist", 60764.24),
       ("Vice president of marketing",268663.67),
       ("Assembly Supervisor", 65842.42),
       ("Assistant Plant Manager", 91126.43),
       ("Chief Manufacturing Executive", 290300.76),
       ("Chief Quality Control Executive", 225200.24),
       ("Civil Engineering Supervisor", 94146),
       ("Controls Engineer", 102802.35),
       ("Director of Quality Management", 110946.35),
       ("Distribution Manager", 100476);

INSERT INTO employees (first_name, last_name)
VALUE   ("Juliette", "Noble"),
        ("Donavan", "Nicholson"),
        ("Katherine", "Benton"),
        ("Ali", "Garza"),
        ("Iris", "Rocha"),
        ("Livia", "Leon"),
        ("Kenneth", "Adkins"),
        ("Arianna", "Andersen"),
        ("Reagan", "Henderson"),
        ("Rafael", "Lindsey"),
        ("Lexi", "Meyers"),
        ("Ayaan", "Hubbard"),
        ("Calvin", "Sparks"),
        ("Aimee", "Mora"),
        ("Rodney", "Holmes"),
        ("Gracie", "Houston"),
        ("Clare", "Logan"),
        ("Kamari", "Hobbs"),
        ("Laurel", "Waters"),
        ("Lilianna", "Compton"),
        ("Hugh", "Alvarado"),
        ("Meredith", "Sharp"),
        ("Cameron", "Mcfarland"),
        ("Averie", "Chavez"),
        ("Pierce", "Meyers"),
        ("Kiley", "Benjamin"),
        ("Tyler" "Benitez"),
        ("Cayden", "Pittman"),
        ("Madilynn", "Santana"),
        ("Justin", "Prince"),
        ("Dorian", "Thomas"),
        ("Madelyn", "Sullivan"),
        ("Camryn", "Cameron"),
        ("Lilianna", "Ball"),
        ("Austin", "Ford"),
        ("Selena", "Barrera"),
        ("Selah", "Kaufman"),
        ("Kade", "Hale"),
        ("Patrick", "Stevens"),
        ("Dulce", "Phillips");
